name: "🐛 Bug Report"
description: "Report a bug or issue"
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the information below so we can reproduce and fix it quickly.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Select the component where the issue occurs
      options:
        - Frontend UI
        - Backend Service & API
        - Document Reader Service
        - Vector Database
        - Model Service
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue in detail
      placeholder: "Describe what is going wrong..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: "What should happen instead..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Log Collection Guide

        Please collect logs using the command below:

        docker compose logs -f --tail=1000 app docreader postgres

        Reproduce the issue and paste relevant logs in the field below.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Collect and paste logs following the guide above
      placeholder: |
        Paste logs collected from:
        docker compose logs -f --tail=1000 app docreader postgres
      render: shell

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your current operating system
      placeholder: "e.g. macOS 13.0, Ubuntu 20.04, Windows 11"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I searched existing issues and confirmed this is a new issue
          required: true
