name: "✨ Feature Request"
description: "Suggest a new feature or an improvement"
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature request! Please describe your proposal in detail so we can evaluate it effectively.

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Select the component related to this request
      options:
        - Frontend UI
        - Backend Service & API
        - Document Reader Service
        - Vector Database
        - Model Service
        - Configuration Management
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the current problem or limitation
      placeholder: "What problem or limitation are you facing?"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or improvement you want
      placeholder: "How would you like this to be solved?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative approaches you considered
      placeholder: "Did you consider other solutions?"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How would you rate the priority of this request?
      options:
        - Low - Can be considered later
        - Medium - Has clear value
        - High - Important for workflow
        - Urgent - Blocks important work
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe the concrete scenario for this feature
      placeholder: "When and how would you use this feature?"

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information, screenshots, or links
      placeholder: "Add any other relevant details..."

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I searched existing issues and confirmed this is a new feature request
          required: true
        - label: I understand this request may require discussion and evaluation
          required: true
