name: "❓ Question"
description: "Ask a question about WeKnora or request help"
title: "[Question]: "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Please provide enough context so we can help you effectively.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: Select the category of your question
      options:
        - Installation & Deployment
        - Configuration
        - Usage
        - Performance
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question Details
      description: Describe your question in detail
      placeholder: "What issue are you facing, and what help do you need?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Background Information
      description: Provide relevant background details
      placeholder: |
        - What are you trying to do?
        - What result did you expect?
        - What have you already tried?

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your current operating system
      placeholder: "e.g. macOS 13.0, Ubuntu 20.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Other Environment Details
      description: Provide any additional environment information
      placeholder: |
        - WeKnora version: [e.g. v1.0.0]
        - Deployment method: [e.g. Docker, source build]
        - Other relevant details...

  - type: markdown
    attributes:
      value: |
        ## 📋 Log Collection Guide (If Needed)

        If this question involves errors or debugging, collect logs using:

        ```bash
        docker compose logs -f --tail=1000 app docreader postgres
        ```

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste logs or error messages here if available
      placeholder: "Paste relevant logs or error messages..."
      render: shell

  - type: textarea
    id: research
    attributes:
      label: Resources Already Checked
      description: List docs, issues, or resources you already reviewed
      placeholder: |
        - Docs checked: [e.g. README.md, API.md]
        - Issues checked: [e.g. #123, #456]
        - Other resources: [e.g. official docs, Stack Overflow]

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I searched existing issues and documentation
          required: true
        - label: I provided enough information to explain the question
          required: true
